# Feature state types
FEATURE_SEGMENT = "FEATURE_SEGMENT"
IDENTITY = "IDENTITY"
ENVIRONMENT = "ENVIRONMENT"

# Feature state statuses
COMMITTED = "COMMITTED"
DRAFT = "DRAFT"

STALE_FLAGS_TAG_LABEL = "Stale"
